
spring:
  application:
    name: gpmall-gateway
  cloud:
    gateway:
      routes:
        - id: baidu-route
          uri: https://www.baidu.com
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
server:
  port: 80